import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const read = file => fs.readFileSync(path.join(process.cwd(), file), 'utf8')
const main = read('electron/main.js')
const runtime = read('electron/networkRuntime.js')
const provider = read('src/lib/useNetworkStatus.jsx')
const dashboard = read('src/pages/Dashboard/Dashboard.jsx')
const dashboardSession = read('src/pages/Dashboard/dashboardSession.js')
const preload = read('electron/preload.js')
const lanCheck = read('src/pages/LanCheck/LanCheck.jsx')

describe('centralized native network runtime', () => {
    it('keeps native commands shell-free and behind shared collectors', () => {
        expect(main).not.toContain("const { exec, execFile, spawn } = require('child_process')")
        expect(main).not.toContain('function run(cmd')
        expect(main).toContain("runProgram('powershell', [")
        expect(main).toContain("runProgram('netsh', ['wlan', 'show', 'interfaces']")
        expect(main).toContain("runProgram('ipconfig', ['/all']")
        expect(main).toContain('const networkRuntime = new NetworkRuntime({')
        expect(main).toMatch(/(?:trustedIpc|ipcMain)\.handle\('get-network-snapshot'/)
        expect(main).toContain('hash: \'/dashboard\'')
    })

    it('uses cheap fingerprint detection, single-flight enrichment, and one global Wi-Fi observer', () => {
        expect(runtime).toContain('fingerprintIntervalMs = 5000')
        expect(runtime).toContain('refreshIntervalMs = 60000')
        expect(runtime).toContain('telemetryIntervalMs = 10000')
        expect(runtime).toContain('if (this.refreshPromise)')
        expect(runtime).toContain('if (this.telemetryPromise)')
        expect(runtime).toContain('setTelemetryActive(active)')
        expect(main).toContain('telemetryAlwaysActive: false')
        expect(main).toContain("win.on('show', resumeNetworkTelemetry)")
        expect(main).toContain("win.on('restore', resumeNetworkTelemetry)")
        expect(main).toContain("win.on('minimize', pauseNetworkTelemetry)")
        expect(main).toContain("win.on('hide', pauseNetworkTelemetry)")
        expect(main).toContain("win.webContents.send('window:visibility'")
        expect(preload).toContain("ipcRenderer.on('window:visibility', handler)")
        expect(main).toContain('readFingerprint: currentInterfaceFingerprint')
        expect(main).toContain('readTelemetry: async ({ generation } = {}) =>')
        expect(main).toContain('fingerprintNetworkInterfaces(os.networkInterfaces(), fastDnsServers())')
    })

    it('does not reconstruct network state through renderer polling and destructive timeouts', () => {
        expect(provider).toContain('bridge.getNetworkSnapshot()')
        expect(provider).toContain('bridge.onNetworkSnapshot')
        expect(provider).not.toContain('withTimeout')
        expect(provider).not.toContain('STRUCTURAL_POLL_MS')
        expect(provider).not.toContain('bridge.getNetworkInterfaces()')
        expect(provider).not.toContain('bridge.getNetworkContext()')
        expect(provider).not.toContain('bridge.getWifiInfo()')
        expect(provider).not.toContain('bridge.getDnsServers()')
        expect(provider).not.toContain('bridge.getVpnStatus()')
        expect(provider).toContain('TERMINAL_ENRICHMENT_STATES')
        expect(provider).toContain('revealWhenCoherent')
    })

    it('keeps the skeleton gate and measures one complete non-overlapping round per tick', () => {
        expect(dashboard).toContain('if (!ready) return <DashboardSkeleton />')
        expect(dashboard).toContain('const round = await runSharedDashboardProbe({')
        expect(dashboard).toContain('externalTargets: HOSTS')
        expect(dashboard).toContain('ping: target => bridge.pingSingle(target)')
        expect(dashboard).toContain('await doPingRound()')
        expect(dashboard).toContain('if (!appVisible)')
        expect(dashboard).toContain('samplingVisibleRef.current = appVisible')
        expect(dashboardSession).toContain('const current = probeRoundInFlightByKey.get(key)')
        expect(dashboardSession).toContain('if (current) return current')
        expect(dashboardSession).toContain('const pending = measureProbeRound({')
        expect(dashboard).not.toContain('nextProbeTarget')
        expect(dashboard).not.toContain('setDashboardTelemetryActive')
    })

    it('keeps user-started LAN workloads bounded, cancellable, and separate from background work', () => {
        expect(main).toContain('const PING_CONCURRENCY = safeMode ? 4 : 32')
        expect(main).toContain('const RETRY_CONCURRENCY = safeMode ? 6 : 12')
        expect(main).toContain('Parallel name resolution + vendor lookup (concurrency = 8)')
        expect(main).toContain('Math.min(12, Number.parseInt(String(payload?.hostConcurrency || 4)')
        expect(main).toContain('Math.min(64, Number.parseInt(String(options?.tcpConcurrency || 24)')
        expect(main).toContain('Math.min(24, Number.parseInt(String(options?.udpConcurrency || 8)')
        expect(main).toMatch(/(?:trustedIpc|ipcMain)\.on\('lan-security-scan-cancel'/)
        expect(main).toMatch(/(?:trustedIpc|ipcMain)\.on\('lan-scan-cancel'/)
        expect(lanCheck).toContain('const safeTcpConcurrency = safeMode ? 6 : undefined')
        expect(lanCheck).toContain('const safeUdpConcurrency = safeMode ? 3 : undefined')
        expect(lanCheck).toContain('? Math.max(1, Math.min(3, Math.ceil(cfg.concurrency / 12)))')
    })
})
